'use server'

import { revalidatePath } from 'next/cache'
import { createAction } from '@/lib/actions/wrapper'
import client from '@/lib/api/client'
import {
  createStockAdjustmentSchema,
  type CreateStockAdjustmentInput,
  type StockAdjustment,
  type StockAdjustmentListResponse,
} from '../schema/stock-adjustment.schema'

// The idempotency key is generated by the caller once per logical submission, so a
// resubmit of the same confirmed adjustment collapses on the API instead of applying twice.
export const createStockAdjustmentAction = createAction(
  { name: 'createStockAdjustmentAction', requireAuth: true, requiredRole: 'Admin' },
  async (data: CreateStockAdjustmentInput, idempotencyKey: string) => {
    const body = createStockAdjustmentSchema.parse(data)
    const res = await client.post('/api/v1/stock-adjustments', body, {
      headers: { 'X-Idempotency-Key': idempotencyKey },
    })
    revalidatePath('/stock-adjustment')
    revalidatePath('/stock')
    return res.data.data as StockAdjustment
  }
)

export const getStockAdjustmentsAction = createAction(
  { name: 'getStockAdjustmentsAction', requireAuth: true, requiredRole: 'Admin' },
  async (page: number = 1, pageSize: number = 20, distributorId?: number) => {
    const res = await client.get('/api/v1/stock-adjustments', {
      params: { page, pageSize, distributorId: distributorId || undefined },
    })
    const body = res.data
    return {
      adjustments: body.data as StockAdjustmentListResponse['adjustments'],
      totalCount: body.pagination?.total ?? 0,
      page: body.pagination?.page ?? page,
      pageSize: body.pagination?.pageSize ?? pageSize,
    } satisfies StockAdjustmentListResponse
  }
)

export const getStockAdjustmentAction = createAction(
  { name: 'getStockAdjustmentAction', requireAuth: true, requiredRole: 'Admin' },
  async (id: number) => {
    const res = await client.get(`/api/v1/stock-adjustments/${id}`)
    return res.data.data as StockAdjustment
  }
)
