CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "EntityType" text NOT NULL,
    "EntityId" text NOT NULL,
    "Operation" text NOT NULL,
    "OldValues" text,
    "NewValues" text,
    "ChangedBy" uuid NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    "IpAddress" text,
    "CorrelationId" text,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "IdempotencyKeys" (
    "Key" text NOT NULL,
    "ResponseJson" text NOT NULL,
    "StatusCode" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_IdempotencyKeys" PRIMARY KEY ("Key")
);

CREATE TABLE "RevokedTokens" (
    "Jti" text NOT NULL,
    "RevokedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RevokedTokens" PRIMARY KEY ("Jti")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    "DeviceId" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" integer NOT NULL,
    "TokenHash" text NOT NULL,
    "FamilyId" uuid NOT NULL,
    "DeviceId" text NOT NULL,
    "IsConsumed" boolean NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_AuditLogs_ChangedAt" ON "AuditLogs" ("ChangedAt");

CREATE INDEX "IX_AuditLogs_CorrelationId" ON "AuditLogs" ("CorrelationId");

CREATE INDEX "IX_AuditLogs_EntityType_EntityId" ON "AuditLogs" ("EntityType", "EntityId");

CREATE INDEX "IX_IdempotencyKeys_ExpiresAt" ON "IdempotencyKeys" ("ExpiresAt");

CREATE INDEX "IX_RefreshTokens_FamilyId" ON "RefreshTokens" ("FamilyId");

CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_RevokedTokens_ExpiresAt" ON "RevokedTokens" ("ExpiresAt");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_Users_IsDeleted" ON "Users" ("IsDeleted");

CREATE UNIQUE INDEX "IX_Users_Phone" ON "Users" ("Phone");

CREATE INDEX "IX_Users_UpdatedAt" ON "Users" ("UpdatedAt");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260306044536_InitialInfrastructure', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users"
    ALTER COLUMN "UpdatedBy" TYPE integer
    USING CASE WHEN "UpdatedBy" ~ '^\d+$' THEN "UpdatedBy"::integer ELSE NULL END,
    ALTER COLUMN "CreatedBy" TYPE integer
    USING CASE WHEN "CreatedBy" ~ '^\d+$' THEN "CreatedBy"::integer ELSE NULL END;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260306051824_AuditFields_CreatedUpdatedByInt', '8.0.24');

COMMIT;

START TRANSACTION;

CREATE TABLE "Distributors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Address" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL,
    "Alias" text NOT NULL,
    "Code" text NOT NULL,
    "TradeDiscount" numeric(5,2) NOT NULL,
    "Commission" numeric(5,2) NOT NULL,
    "Remark" text,
    "VatRegNo" text,
    "Latitude" double precision,
    "Longitude" double precision,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" integer,
    "UpdatedBy" integer,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Distributors" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Distributors_Code" ON "Distributors" ("Code");

CREATE UNIQUE INDEX "IX_Distributors_Email" ON "Distributors" ("Email");

CREATE INDEX "IX_Distributors_IsDeleted" ON "Distributors" ("IsDeleted");

CREATE UNIQUE INDEX "IX_Distributors_Phone" ON "Distributors" ("Phone");

CREATE INDEX "IX_Distributors_UpdatedAt" ON "Distributors" ("UpdatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260306083716_AddDistributorEntity', '8.0.24');

COMMIT;

START TRANSACTION;

DROP INDEX "IX_Distributors_Code";

ALTER TABLE "Distributors" DROP COLUMN "Code";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260306090257_RemoveDistributorCodeColumn', '8.0.24');

COMMIT;

START TRANSACTION;

ALTER TABLE "Distributors"
                  ALTER COLUMN "Alias" TYPE integer
                  USING "Alias"::integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260306090604_ConvertDistributorAliasToInt', '8.0.24');

COMMIT;

