'use server'

import { revalidatePath } from 'next/cache'
import { createAction } from '@/lib/actions/wrapper'
import client from '@/lib/api/client'
import {
  createStockTransferSchema,
  type CreateStockTransferInput,
  type StockTransfer,
  type StockTransferListResponse,
} from '../schema/stock-transfer.schema'

// The idempotency key is generated by the caller once per logical submission, so a
// resubmit of the same confirmed transfer collapses on the API instead of moving stock twice.
export const createStockTransferAction = createAction(
  { name: 'createStockTransferAction', requireAuth: true, requiredRole: 'Admin' },
  async (data: CreateStockTransferInput, idempotencyKey: string) => {
    const body = createStockTransferSchema.parse(data)
    const res = await client.post('/api/v1/stock-transfers', body, {
      headers: { 'X-Idempotency-Key': idempotencyKey },
    })
    revalidatePath('/stock-transfer')
    revalidatePath('/stock')
    return res.data.data as StockTransfer
  }
)

export const getStockTransfersAction = createAction(
  { name: 'getStockTransfersAction', requireAuth: true, requiredRole: 'Admin' },
  async (page: number = 1, pageSize: number = 20, distributorId?: number) => {
    const res = await client.get('/api/v1/stock-transfers', {
      params: { page, pageSize, distributorId: distributorId || undefined },
    })
    const body = res.data
    return {
      transfers: body.data as StockTransferListResponse['transfers'],
      totalCount: body.pagination?.total ?? 0,
      page: body.pagination?.page ?? page,
      pageSize: body.pagination?.pageSize ?? pageSize,
    } satisfies StockTransferListResponse
  }
)

export const getStockTransferAction = createAction(
  { name: 'getStockTransferAction', requireAuth: true, requiredRole: 'Admin' },
  async (id: number) => {
    const res = await client.get(`/api/v1/stock-transfers/${id}`)
    return res.data.data as StockTransfer
  }
)
